apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.nodeName }}
    namespace: {{ $.Values.metadata.namespace }}
        {{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
    {{- end }}
    labels:
      run: {{ .Values.nodeName }}
      app.kubernetes.io/name: {{ .Values.nodeName }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
spec:
    selector:
      app: {{ .Values.nodeName }}
    type: {{ .Values.service.type }}    
    ports:
      - protocol: TCP 
        port: 8080
        targetPort: 8080
        nodePort: {{ .Values.service.nodePort }}
---







