---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:karankk1991/gitopsall.git
    path: charts/podinfo
    ref: master
  values:
    image: stefanprodan/podinfo:dev-hdtwcel9
    replicaCount: 1
    hpa:
      enabled: false
