apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: orderer
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
  
spec:
  releaseName: orderer
  chart:
    git: git@github.com:karankk1991/gitopsall.git
    path: charts/testpod
    ref: master
  values:
    replicaCount: 1

    nodeName: orderer
    env: dev
    
    #Provide the replica set for node deployed
    #Eg. replicas: 1
    replicas: 1
    
    metadata:
      #Provide the namespace for organization's peer
      #Eg. namespace: default
      namespace: default
    
    image:
      #Provide the containerName of image
      #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
      containerName: luksa/kubia
      #Provide the name of image for init container
      #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
      #initContainerName: adopfrablockchain.azurecr.io/alpine-utils:1.0
      #Provide the image pull secret of image
      #Eg. pullSecret: regcred
      #imagePullSecret: regcred


     