# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the Name for node to be deployed
#Eg. nodeName: bank1
nodeName: 

image:
  #Provide the name of image for container
  #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
  containerName: 
  #Provide the name of image for init container
  #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
  initContainerName: 
  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  imagePullSecret: 

resources:
  #Provide the limit memory for node
  #Eg. limits: "3Gi"
  limits: 
  #Provide the requests memory for node
  #Eg. requests: "2Gi"
  requests: 

storage:
  #Provide the memory for node
  #Eg. memory: 4Gi
  memory:
  mountPath:  

service:
  #Provide the type of service
  #Eg. type: NodePort
  type: 
  tcp:
    #Provide the tcp port for node 
    #Eg. port: 9101
    port:
    #Provide the tcp node port for node 
    #Eg. port: 32001
    nodePort: 
    #Provide the tcp targetPort for node 
    #Eg. targetPort: 1521
    targetPort:
  web:
    #Provide the web node port for node 
    #Eg. port: 32080
    nodePort:  
    #Provide the tcp targetPort for node 
    #Eg. targetPort: 81
    targetPort:
    #Provide the tcp node port for node 
    #Eg. port: 8080
    port: