apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: bank1-database-password-change
  namespace: bank1-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: bank1-database-password-change
  chart:
    git: ssh://git@innersource.accenture.com/dlta/dlt-corda-gitops-all.git
    path: charts/h2-password-change
    ref: master
  values:
    replicaCount: 1


    #Provide the Name for node to be deployed
    #Eg. nodeName: bank1
    nodeName: bank1
    
    
    metadata:
      #Provide the namespace for organization's peer
      #Eg. namespace: default
      namespace: bank1-ns
    
    image:
      #Provide the name of image for container
      #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
      containerName: adopfrablockchain.azurecr.io/h2:2018
      #Provide the name of image for init container
      #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
      initContainerName: adopfrablockchain.azurecr.io/alpine-utils:1.0
      #Provide the image pull secret of image
      #Eg. pullSecret: regcred
      imagePullSecret: regcred

       
    #Provide the jdbc connection url
    #Eg. jdbcUrl: jdbc:h2:tcp://bank1db:9101/persistence
    jdbcUrl: jdbc:h2:tcp://bank1db:9101/persistence
    #Provide the url for health check
    #Eg. dbUrl: bank1db
    dbUrl: bank1db
    #Provide the port for health check
    #Eg. dbPort: 9101
    dbPort: 9101
         
    
    vault:
      #Provide the vault server address
      #Eg. address: http://54.226.163.39:8200
      address: http://52.90.141.182:8200
      #Provide the vaultrole
      #Eg. role: vault-role
      role: vault-role
      #Provide the authpath
      #Eg. authpath: cordabank1
      authpath: cordabank1
      #Provide the serviceaccountname
      #Eg. serviceaccountname: vault-auth-issuer
      serviceaccountname: vault-auth-bank1
      #Provide the secretprefix
      #Eg. dbsecretprefix: bank1/credentials/database
      dbsecretprefix: bank1/credentials/database
    
    db:
      #Provide the interval in seconds you want to iterate till db to be ready 
      #Eg. readinesscheckinterval: 5
      readinesscheckinterval: 10
      #Provide the threshold till you want to check if specified db up and running
      #Eg. readinessthreshold: 2
      readinessthreshold: 15      