apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: centralbank-node
  namespace: centralbank-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: centralbank-node
  chart:
    git: ssh://git@innersource.accenture.com/dlta/dlt-corda-gitops-all.git
    path: charts/node
    ref: master
  values:
    replicaCount: 1


    #Provide the nodeName for node
    #Eg. nodeName: bank1
    nodeName: centralbank
    
    #Provide the replica set for node deployed
    #Eg. replicas: 1
    replicas: 1
    
    metadata:
      #Provide the namespace for organization's peer
      #Eg. namespace: default
      namespace: centralbank-ns
      
    image:
      #Provide the containerName of image
      #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
      containerName: adopfrablockchain.azurecr.io/corda:3.3.0-corda-test-20190219
      #Provide the name of image for init container
      #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
      initContainerName: adopfrablockchain.azurecr.io/alpine-utils:1.0
      #Provide the image pull secret of image
      #Eg. pullSecret: regcred
      imagePullSecret: regcred
    
    #For more information for node.Conf fields please refer to: https://docs.corda.r3.com/corda-configuration-file.html
    nodeConf:
      #The host and port on which the node is available for protocol operations over ArtemisMQ.
      p2p:
        url: 35.175.35.240
        port: 10002
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: 
          sslKeystorePath: "/sslkeystore.jks"
          trustStoreFilePath: "/truststore.jks"
      #Provide the legalName for node
      #Eg. legalName: "O=Bank1,L=London,C=GB,CN=Bank1"
      legalName: "O=Regulator,L=Dublin,C=IR,CN=Central Bank"
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
      notary:
        validating: false
      detectPublicIp: true
      extraAdvertisedServiceIds: [ "" ]
      database:
        serverNameTablePrefix: ""
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
        runMigration: true
      #Provide the h2Url for node
      #Eg. h2Url: bank1h2
      dbUrl: centralbankdb
      #Provide the h2Port for node
      #Eg. h2Port: 9101
      dbPort: 9103
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://centralbankdb:9103/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      #Provide the nms for node
      #Eg. nms: "http://rp-elb-corda-kube-check-cluster2-164630566.us-east-1.elb.amazonaws.com:30050"
      networkMapURL: "http://rp-elb-corda-kube-check-cluster2-164630566.us-east-1.elb.amazonaws.com:30080"
      doormanURL: "http://rp-elb-corda-kube-check-cluster2-164630566.us-east-1.elb.amazonaws.com:30081"
      compatibilityZoneURL: 
      webAddress: "localhost:10004"
      #Provide the jar Version for corda jar and finanace jar
      #Eg. jarVersion: 3.3-corda
      jarVersion: 3.3-corda
      #Provide the devMode for corda node
      #Eg. devMode: true
      devMode: false
      #Provide the useHTTPS for corda node
      #Eg. useHTTPS: false
      useHTTPS: true
      #Provide the enviroment variables to be set
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: MOUNT_PATH
          value: /opt/corda
    
    credentials:
      #Provide the dataSourceUser for corda node
      #Eg. dataSourceUser: sa
      dataSourceUser: sa
      #Provide the rpcUser for corda node
      #Eg. rpcUser: bank1operations
      rpcUser:
        - name: centralbankoperations
          permissions: [ALL]
    
    volume:
      #Provide the base path
      #Eg. mountPath: "/opt/h2-data"
      mountPath: /opt/corda
      
    resources:
      #Provide the limit memory for node
      #Eg. limits: "3Gi"
      limits: "2Gi"
      #Provide the requests memory for node
      #Eg. requests: "2Gi"
      requests: "1Gi"
    
    storage:
      #Provide the memory for node
      #Eg. memory: 4Gi
      memory: 4Gi
      #Provide the name for node
      #Eg. name: bank1nodesc
      name: centralbanknodesc

      
    service:
    # Note: Target ports are dependent on image being used. Please change them accordingly 
    #       nodePort should be kept empty while using service type as ClusterIP ( Values.service.type ) 
      #Provide the type of service
      #Eg. type: NodePort or LoadBalancer etc 
      type: NodePort
      p2p:
        #Provide the p2p port for node 
        #Eg. port: 10007
        port: 10013
        #Provide the p2p node port for node 
        #Eg. port: 30007
        nodePort: 30013
        #Provide the p2p targetPort for node 
        #Eg. targetPort: 30007
        targetPort: 10002
      rpc:
        #Provide the rpc port for node 
        #Eg. port: 10008
        port: 10014
        #Provide the p2p targetPort for node 
        #Eg. targetPort: 10003
        targetPort: 10003
        #Provide the p2p node port for node 
        #Eg. nodePort: 30007
        nodePort: 30014
      rpcadmin:
        #Provide the rpcadmin port for node 
        #Eg. port: 10108
        port: 10114
        #Provide the p2p targetPort for node 
        #Eg. targetPort: 10005
        targetPort: 10005
        #Provide the p2p node port for node 
        #Eg. nodePort: 30007
        nodePort: 30114
      #   annotations:
      #     key: "value"
      annotations: {}
    
    deployment:
      #   annotations:
      #     key: "value"
      annotations: {}
    
    pvc:
      #   annotations:
      #     key: "value"
      annotations: {}
    
    vault:
      #Provide the vault server address
      #Eg. address: http://34.228.219.208:8200
      address: http://52.90.141.182:8200
      #Provide the vaultrole
      #Eg. role:
      role: vault-role
      #Eg. authpath:
      authpath: cordacentralbank
      #Eg. serviceaccountname: vault-auth-issuer
      serviceaccountname: vault-auth-centralbank
      #Provide the secretprefix
      #Eg. dbsecretprefix: bank1/credentials/database
      dbsecretprefix: centralbank/credentials/database
      #Provide the secretprefix
      #Eg. rpcusersecretprefix: bank1/credentials/rpcusers
      rpcusersecretprefix: centralbank/credentials/rpcusers
      #Provide the secretprefix
      #Eg. tokensecretprefix: bank1/credentials/vaultroottoken
      tokensecretprefix: centralbank/credentials/vaultroottoken
      #Provide the secretprefix
      #Eg. keystoresecretprefix: bank1/credentials/keystore
      keystoresecretprefix: centralbank/credentials/keystore
      #Provide the secretprefix
      #Eg. certsecretprefix: bank1/certs
      certsecretprefix: centralbank/certs
    
    db:
      #Provide the interval in seconds you want to iterate till db to be ready 
      #Eg. readinesscheckinterval: 5
      readinesscheckinterval: 10
      #Provide the threshold till you want to check if specified db up and running
      #Eg. readinessthreshold: 2
      readinessthreshold: 15
