apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: centralbank-web
  namespace: centralbank-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: centralbank-web
  chart:
    git: ssh://git@innersource.accenture.com/dlta/dlt-corda-gitops-all.git
    path: charts/springbootwebserver
    ref: master
  values:
    replicaCount: 1


    #Provide the nodeName for node
    #Eg. nodeName: bank1web
    nodeName: centralbankweb
    
    metadata:
      namespace: centralbank-ns
    
    image:
      #Provide the containerName of image for main container
      #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
      containerName: adopfrablockchain.azurecr.io/springboot-webserver:1.1.1-springboot-webserver
      #Provide the name of image for init container
      #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
      initContainerName: adopfrablockchain.azurecr.io/alpine-utils:1.0
      #Provide the image pull secret of image
      #Eg. pullSecret: regcred
      imagePullSecret: regcred
    
    smartContract:
      #Provide the smart contract name you need to execute
      #Eg. name: corda-ibt-webserver-1.1.0.jar
      name: corda-ibt-webserver-1.1.0.jar
      #Provide relative smart contract path from mouth path 
      #Eg. path: cordapps
      path: cordapps
      #Provide java option
      #Eg. JAVA_OPTIONS : -Xmx512m  
      JAVA_OPTIONS : -Xmx512m  
    
    volume:
      #Provide the base path
      #Eg. mountPath: "/opt/h2-data"
      mountPath: /opt/corda
      
    nodeConf:
      #Provide the Name of the corda node for node.conf
      #Eg. node: bank1
      node: centralbank
      #Provide the node Rpc Port for node
      #Eg. nodeRpcPort: 10008
      nodeRpcPort: 10014
      #Provide the node Rpc Admin Port for node
      #Eg. nodeRpcAdminPort: 10108
      nodeRpcAdminPort: 10114
      #Provide the legalName for node
      #Eg. legalName: "O=Bank1,L=London,C=GB,CN=Bank1"
      legalName: "O=Regulator,L=London,C=GB,CN=Central Bank"
    
      #Provide the devMode for corda node
      #Eg. devMode: true
      devMode: false
      #Provide the useHTTPS for corda node
      #Eg. useHTTPS: false
      useHTTPS: false
      useSSL: false
      controllerName: Controller
      trustStorePath: /opt/corda/certificates/sslkeystore.jks
      trustStoreProvider: jks
      tlsAlias: cordaclienttls
      port: 10004
    
    credentials:
      #Provide the dataSourceUser for corda node
      #Eg. dataSourceUser: sa
      dataSourceUser: sa
      #Provide the rpcUser for corda node
      #Eg. rpcUser: bank1operations
      rpcUser: centralbankoperations
    
    resources:
      #Provide the limit memory for node
      #Eg. limits: "3Gi"
      limits: "1Gi"
      #Provide the requests memory for node
      #Eg. requests: "2Gi"
      requests: "1Gi"
    
    storage:
      name: centralbankwebnodesc
      #Provide the memory for node
      #Eg. memory: 4Gi
      memory: 4Gi

    
    web:
    # Note: Target ports are dependent on image being used. Please change them accordingly 
    #       nodePort should be kept empty while using service type as ClusterIP ( Values.service.type ) 
      #Provide the web port for node
      #Eg. port: 10009
      port: 10015
      #Provide the web node port for node 
      #Eg. port: 30009
      nodePort: 30015 
      #Provide the web targetPort for node 
      #Eg. targetPort: 10004
      targetPort: 10004
    
    service:
    # Note: Target ports are dependent on image being used. Please change them accordingly 
    #       nodePort should be kept empty while using service type as ClusterIP ( Values.service.type ) 
      #Provide the type of service
      #Eg. type: NodePort or LoadBalancer etc
      type: NodePort
      #   annotations:
      #     key: "value"
      annotations: {}
    
    deployment:
      #   annotations:
      #     key: "value"
      annotations: {}
    
    pvc:
      #   annotations:
      #     key: "value"
      annotations: {}
      
    vault:
      #Provide the vault server address
      #Eg. address: http://54.226.163.39:8200
      address: http://52.90.141.182:8200
      #Provide the vaultrole
      #Eg. role: vault-role
      role: vault-role
      #Provide the authpath
      #Eg. authpath: cordabank1
      authpath: cordacentralbank
      #Provide the serviceaccountname
      #Eg. serviceaccountname: vault-auth-issuer
      serviceaccountname: vault-auth-centralbank
      #Provide the secretprefix
      #Eg. secretprefix: issuer
      secretprefix: centralbank
      #Provide the secretprefix
      #Eg. rpcusersecretprefix: bank1/credentials/rpcusers
      rpcusersecretprefix: centralbank/credentials/rpcusers 
      #Provide the secretprefix
      #Eg. keystoresecretprefix: bank1/credentials/keystore
      keystoresecretprefix: centralbank/credentials/keystore
      #Provide the secretprefix
      #Eg. certsecretprefix: bank1/certs
      certsecretprefix: centralbank/certs
      
    node:
      #Provide the interval in seconds you want to iterate till node to be ready
      #Eg. readinesscheckinterval: 5
      readinesscheckinterval: 10
      #Provide the threshold till you want to check if specified node up and running
      #Eg. readinessthreshold: 2
      readinessthreshold: 15