# This is a YAML-formatted file.
# This should be produced by build

#Provide the nodeName for node
#Eg. nodeName: bank1
nodeName: 

#Provide the replica set for node deployed
#Eg. replicas: 1
replicas: 

metadata:
  #Provide the namespace
  #Eg. namespace: default
  namespace: 

image:
  #Provide the containerName of image
  #Eg. containerName: adopfrablockchain.azurecr.io/h2:2018
  containerName: 
  #Provide the name of image for init container
  #Eg. name: adopfrablockchain.azurecr.io/alpine-utils:1.0
  initContainerName: 
  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  imagePullSecret: 

#For more information for node.Conf fields please refer to: https://docs.corda.r3.com/corda-configuration-file.html
nodeConf:
  #The host and port on which the node is available for protocol operations over ArtemisMQ.
  p2p:
    url: 
    port: 
  rpcSettings:
    useSsl: 
    standAloneBroker: 
    address: 
    adminAddress: 
    ssl:
      certificatesDirectory: 
      sslKeystorePath: 
      trustStoreFilePath: 
  #Provide the legalName for node
  #Eg. legalName: "O=Bank1,L=London,C=GB,CN=Bank1"
  legalName: 
  messagingServerAddress:
  jvmArgs:
  systemProperties:
  sshd:
    port:
  exportJMXTo:
  transactionCacheSizeMegaBytes: 
  attachmentContentCacheSizeMegaBytes: 
  attachmentCacheBound: 
  notary:
    validating: 
  detectPublicIp: 
  extraAdvertisedServiceIds: 
  database:
    serverNameTablePrefix: 
    transactionIsolationLevel: 
    exportHibernateJMXStatistics: 
    runMigration: 
  #Provide the h2Url for node
  #Eg. h2Url: bank1h2
  dbUrl: 
  #Provide the h2Port for node
  #Eg. h2Port: 9101
  dbPort: 
  dataSourceClassName: 
  dataSourceUrl: 
  jarPath: 
  #Provide the nms for node
  #Eg. nms: "http://rp-elb-fra-corda-kube-cluster7-2016021309.us-west-1.elb.amazonaws.com:30050"
  networkMapURL: 
  doormanURL: 
  compatibilityZoneURL:
  webAddress: 
  #Provide the jar Version for corda jar and finanace jar
  #Eg. jarVersion: 3.3-corda
  jarVersion: 
  #Provide the devMode for corda node
  #Eg. devMode: true
  devMode: 
  #Provide the useHTTPS for corda node
  #Eg. useHTTPS: false
  useHTTPS: 
  #Provide the enviroment variables to be set
  env:
    - name: 
      value: 
    - name: 
      value: 
    - name: 
      value: 
  
credentials:
  #Provide the dataSourceUser for corda node
  #Eg. dataSourceUser: sa
  dataSourceUser: 
  #Provide the rpcUser for corda node
  #Eg. rpcUser: bank1operations
  rpcUser:
    - name: 
      permissions: 
    - name: 
      permissions: 
    - name: 
      permissions: 

volume:
  #Provide the base path
  #Eg. mountPath: "/opt/h2-data"
  mountPath: 

resources:
  #Provide the limit memory for node
  #Eg. limits: "3Gi"
  limits: 
  #Provide the requests memory for node
  #Eg. requests: "2Gi"
  requests: 

storage:
  #Provide the memory for node
  #Eg. memory: 4Gi
  provisioner: 
  #Provide the name for node
  #Eg. name: bank1nodesc
  name: 
  #Provide the memory for node
  #Eg. memory: 4Gi
  memory: 
  parameters:
    #Provide the type for node
    #Eg. type: gp2
    - name: 
      value: 
    # Provide whether the EBS volume should be encrypted or not
    #Eg. encrypted: "true"
    - name: 
      value: 
  #   annotations:
  #     key: "value"
  annotations: 
  
service:
# Note: Target ports are dependent on image being used. Please change them accordingly 
#       nodePort should be kept empty while using service type as ClusterIP ( Values.service.type ) 
  #Provide the type of service
  #Eg. type: NodePort or LoadBalancer etc 
  type: 
  #Provide the cluster ip of service
  #Eg. clusterIP: 10.96.1.1
  clusterIP: 
  p2p:
    #Provide the p2p port for node 
    #Eg. port: 10007
    port: 
    #Provide the p2p node port for node 
    #Eg. port: 30007
    nodePort: 
    #Provide the p2p targetPort for node 
    #Eg. targetPort: 30007
    targetPort: 
  rpc:
    #Provide the rpc port for node 
    #Eg. port: 10008
    port:  
    #Provide the p2p targetPort for node 
    #Eg. targetPort: 10003
    targetPort: 
    #Provide the p2p node port for node 
    #Eg. nodePort: 30007
    nodePort: 
  rpcadmin:
    #Provide the rpcadmin port for node 
    #Eg. port: 10108
    port: 
    #Provide the p2p targetPort for node 
    #Eg. targetPort: 10005
    targetPort: 
    #Provide the p2p node port for node 
    #Eg. nodePort: 30007
    nodePort: 
  #   annotations:
  #     key: "value"
  annotations: 

deployment:
  #   annotations:
  #     key: "value"
  annotations: 

pvc:
  #   annotations:
  #     key: "value"
  annotations: 

vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address: 
  #Provide the vaultrole
  #Eg. role: vault-role
  role: 
  #Provide the authpath
  #Eg. authpath: cordabank1
  authpath: 
  #Provide the serviceaccountname
  #Eg. serviceaccountname: vault-auth-issuer
  serviceaccountname: 
  #Provide the secretprefix
  #Eg. dbsecretprefix: bank1/credentials/database
  dbsecretprefix: 
  #Provide the secretprefix
  #Eg. rpcusersecretprefix: bank1/credentials/rpcusers
  rpcusersecretprefix: 
  #Provide the secretprefix
  #Eg. tokensecretprefix: bank1/credentials/vaultroottoken
  tokensecretprefix: 
  #Provide the secretprefix
  #Eg. keystoresecretprefix: bank1/credentials/keystore
  keystoresecretprefix: 
  #Provide the secretprefix
  #Eg. certsecretprefix: bank1/certs
  certsecretprefix: 

db:
  #Provide the interval in seconds you want to iterate till db to be ready 
  #Eg. readinesscheckinterval: 5
  readinesscheckinterval: 
  #Provide the threshold till you want to check if specified db up and running
  #Eg. readinessthreshold: 2
  readinessthreshold: 