apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.nodeName }}
    {{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
    {{- end }}
    labels:
      run: {{ .Values.nodeName }}
      app.kubernetes.io/name: {{ .Values.nodeName }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
spec:
    type: {{ .Values.service.type }}
    {{- if .Values.service.clusterIP }}
    clusterIP: "{{ .Values.service.clusterIP }}"
    {{- end }}
    selector:
      app: {{ .Values.nodeName }}
    ports:
    - name: p2p
      protocol: TCP
      port: {{ .Values.service.p2p.port }}
      targetPort: {{ .Values.service.p2p.targetPort }}
      {{- if .Values.service.p2p.nodePort }}
      nodePort: {{ .Values.service.p2p.nodePort}}
      {{- end }}
    - name: rpc
      protocol: TCP
      port: {{ .Values.service.rpc.port }}
      targetPort: {{ .Values.service.rpc.targetPort }}
      {{- if .Values.service.rpc.nodePort }}
      nodePort: {{ .Values.service.rpc.nodePort}}
      {{- end }}
    - name: rpcadmin
      protocol: TCP
      port: {{ .Values.service.rpcadmin.port }}
      targetPort: {{ .Values.service.rpcadmin.targetPort }}
      {{- if .Values.service.rpcadmin.nodePort }}
      nodePort: {{ .Values.service.rpcadmin.nodePort}}
      {{- end }}
      
