apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.nodeName }}
    namespace: {{ .Values.metadata.namespace }}
    labels:
      run: {{ .Values.nodeName }}
      app.kubernetes.io/name: {{ .Values.nodeName }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
    type: {{ .Values.service.type }}
    selector:
      app: {{ .Values.nodeName }}
    ports:
    - port: {{ .Values.web.port }}
      nodePort: {{ .Values.web.nodePort}}
      targetPort: {{ .Values.web.targetPort}}
      protocol: TCP
      name: web
